# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a6bcc4e5d5e066d146003920aae5a25c1f25e50eb6e650e7a530cfeaf126addd47273e7dc9e512a05dd93951c2446083cf1cbbe54ee370fa617c909fc57b5ea

test:
  secret_key_base: d8b67b923a39e1c89498a99eb7a202dcad17fc3a4b9950c626f767ca84f53fd5fd5703ec8134743d7c8ce1fee760f2bf79a967e8bba691e21d220f812cc93706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
